import React, {useState, useEffect} from 'react'
import { Container } from 'react-bootstrap'
import { auth } from '../../../firebase-config';


/**
 * 0 - We need the Users from <App /> and use that to find the current user.
 * 1 - This dashboard will display all the inbound messages the user has recived,
 *     it is generated by that random id, and the message-room is eastablished based on it
 * 2 - The user see's all the messages they have incoming, and can click on one to open the
 *     specific message-room, which will have the path of the id.
 */
function MessageDash({ users }) {
    console.log(users);
    return (
        <Container>
            {
                users.map((user) => {
                    if(user.id === auth.currentUser.uid) {
                        return (
                            <h1>{auth.currentUser.uid}</h1>
                            /**
                             * 1 - Logged in user is found, we can now pass this data off to the message-system-card 
                             *     which will display all the messages, so the front-end portion.
                             */

                        )
                    }
                })
            }
            

        </Container>
    )
}

export default MessageDash